auto:    true

brigade:
    name: Code for Seattle
    city:   "Seattle, WA"
    meetup-link: "http://www.meetup.com/Code-for-Seattle/"
    google-group: "https://groups.google.com/forum/#!forum/seattlewiki"
    github: "https://github.com/codeforseattle"
    idea-list: ""

content:
    title: Code for Seattle
    meetup-invite: "http://www.meetup.com/Code-for-Seattle/"
    contact: "info@seattlewiki.net"
    banner: ./images/banner.jpg
    projects:
      - name: SeattleWiki.net
        content: "<a href='http://seattlewiki.net'>SeattleWiki.net</a>"
    footer: "Thanks to Virginia Beach CfA for supplying this site's template, the Noun Project and brockamer@flikr for images,</br> and Jan Jorgensen for converting the template to Jekyll." 

google-analytics:
    use: true
    code: UA-38362883-1
