baseurl: ""

brigade:
    name: Code for Seattle
    city:   "Seattle, WA"
    meetup-link: "http://www.meetup.com/Code-for-Seattle/"
    google-group: "https://groups.google.com/forum/#!forum/codeforseattle"
    github: "https://github.com/codeforseattle"
    idea-list: "http://seattlewiki.net/Code_for_Seattle_ideas"

content:
    title: Code for Seattle
    meetup-invite: "http://www.meetup.com/Code-for-Seattle/"
    contact: "info@seattlewiki.net"
    banner: ./images/banner.jpg
    projects:
      - name: SeattleWiki.net
        content: "<a href='http://seattlewiki.net' target='_blank'>SeattleWiki.net</a>"
      - name: nwdata.org
        content: "<a href='http://nwdata.org' target='_blank'>nwdata.org</a>"
      - name: 'Seattle Food Trucks'
        content: "<a href='http://seattlefoodtrucks.herokuapp.com/' target='_blank'>Seattle Food Trucks</a>"
      - name: 'GeoSub'
        content: "<a href='https://github.com/willscott/geosub' target='_blank'>GeoSub</a>"
      - name: 'Seattle Blogs API'
        content: "<a href='http://seattle-blogs.herokuapp.com/' target='_blank'>Seattle Blogs API</a>"
      - name: Ruby LocalWiki client
        content: "<a href='https://github.com/codeforseattle/localwiki_client' target='_blank'>Ruby LocalWiki client</a>"
      - name: Node.js LocalWiki client
        content: "<a href='https://github.com/codeforseattle/node-localwiki-client' target='_blank'>Node.js LocalWiki client</a>"
    footer: "Thanks to Virginia Beach CfA for supplying this site's template, the Noun Project and brockamer@flikr for images,</br> and Jan Jorgensen for converting the template to Jekyll." 

google-analytics:
    use: true
    code: UA-38362883-1
