baseurl: ""

brigade:
    name: Code for Seattle
    city:   "Seattle, WA"
    meetup-link: "http://www.meetup.com/Code-for-Seattle/"
    google-group: "https://groups.google.com/forum/#!forum/codeforseattle"
    github: "https://github.com/codeforseattle"
    idea-list: "http://seattlewiki.net/Code_for_Seattle_ideas"

content:
    title: Code for Seattle
    meetup-invite: "http://www.meetup.com/Code-for-Seattle/"
    contact: "info@seattlewiki.net"
    banner: ./images/banner.jpg
    projects:
      - name: SeattleWiki.net
        content: "<a href='http://seattlewiki.net' target='_blank'>SeattleWiki.net</a>"
      - name: Localwiki_Client
        content: "<a href='https://github.com/codeforseattle/localwiki_client' target='_blank'>LocalWiki_Client</a>"
    footer: "Thanks to Virginia Beach CfA for supplying this site's template, the Noun Project and brockamer@flikr for images,</br> and Jan Jorgensen for converting the template to Jekyll." 

google-analytics:
    use: true
    code: UA-38362883-1
